# Generated by Django 5.0.1 on 2024-03-21 01:18

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Arl',
            fields=[
                ('idarl', models.AutoField(primary_key=True, serialize=False)),
                ('arl', models.CharField(max_length=45, unique=True)),
            ],
            options={
                'verbose_name': 'ARL',
                'verbose_name_plural': 'ARLS',
            },
        ),
        migrations.CreateModel(
            name='CargoEmpleado',
            fields=[
                ('idcargo_empleado', models.AutoField(primary_key=True, serialize=False)),
                ('cargo_empleado', models.CharField(max_length=45, unique=True)),
            ],
            options={
                'verbose_name': 'cargoempleado',
                'verbose_name_plural': 'cargosempleados',
            },
        ),
        migrations.CreateModel(
            name='CategoriaProducto',
            fields=[
                ('idcategoria_producto', models.AutoField(primary_key=True, serialize=False)),
                ('categoria_producto', models.CharField(max_length=45, unique=True)),
            ],
            options={
                'verbose_name': 'categoriaproducto',
                'verbose_name_plural': 'categoriasproducto',
            },
        ),
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('idciudad', models.AutoField(primary_key=True, serialize=False)),
                ('ciudad', models.CharField(max_length=45)),
            ],
            options={
                'verbose_name': 'Ciudad',
                'verbose_name_plural': 'Ciudades',
            },
        ),
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('idcontacto', models.AutoField(primary_key=True, serialize=False)),
                ('telefono', models.CharField(max_length=20, unique=True)),
                ('correo', models.EmailField(max_length=60, unique=True)),
            ],
            options={
                'verbose_name': 'contacto',
                'verbose_name_plural': 'contactos',
            },
        ),
        migrations.CreateModel(
            name='Eps',
            fields=[
                ('ideps', models.AutoField(primary_key=True, serialize=False)),
                ('eps', models.CharField(max_length=45, unique=True)),
            ],
            options={
                'verbose_name': 'EPS',
                'verbose_name_plural': 'EPSS',
            },
        ),
        migrations.CreateModel(
            name='EstadoComprobante',
            fields=[
                ('idestado_comprobante', models.AutoField(primary_key=True, serialize=False)),
                ('estado_comprobante', models.CharField(max_length=45, unique=True)),
            ],
            options={
                'verbose_name': 'estadocomprobante',
                'verbose_name_plural': 'estadoscomprobante',
            },
        ),
        migrations.CreateModel(
            name='EstadoPQR',
            fields=[
                ('idestado_pqr', models.AutoField(primary_key=True, serialize=False)),
                ('estado_pqr', models.CharField(max_length=45, unique=True)),
            ],
            options={
                'verbose_name': 'estadopqr',
                'verbose_name_plural': 'estadospqr',
            },
        ),
        migrations.CreateModel(
            name='FondoPension',
            fields=[
                ('idfondo_pension', models.AutoField(primary_key=True, serialize=False)),
                ('fondo_pension', models.CharField(max_length=45, unique=True)),
            ],
            options={
                'verbose_name': 'fondopension',
                'verbose_name_plural': 'fondospension',
            },
        ),
        migrations.CreateModel(
            name='FormaPago',
            fields=[
                ('idforma_pago', models.AutoField(primary_key=True, serialize=False)),
                ('forma_pago', models.CharField(max_length=45, unique=True)),
            ],
            options={
                'verbose_name': 'formapago',
                'verbose_name_plural': 'formapago',
            },
        ),
        migrations.CreateModel(
            name='RolUsuario',
            fields=[
                ('idrol_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_rol', models.CharField(max_length=45, unique=True)),
            ],
            options={
                'verbose_name': 'roldeusuario',
                'verbose_name_plural': 'rolesusuario',
            },
        ),
        migrations.CreateModel(
            name='Talla',
            fields=[
                ('idtalla', models.AutoField(primary_key=True, serialize=False)),
                ('talla', models.CharField(max_length=45, unique=True)),
            ],
            options={
                'verbose_name': 'talla',
                'verbose_name_plural': 'tallas',
            },
        ),
        migrations.CreateModel(
            name='TipoCliente',
            fields=[
                ('idtipocliente', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_cliente', models.CharField(max_length=45, unique=True)),
            ],
            options={
                'verbose_name': 'tipocliente',
                'verbose_name_plural': 'tiposcliente',
            },
        ),
        migrations.CreateModel(
            name='TipoComercio',
            fields=[
                ('idtipo_comercio', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_comercio', models.CharField(max_length=45, unique=True)),
            ],
            options={
                'verbose_name': 'tipocomercio',
                'verbose_name_plural': 'tiposcomercio',
            },
        ),
        migrations.CreateModel(
            name='Tipomovimiento',
            fields=[
                ('idtipo_movimiento', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_movimiento', models.CharField(max_length=45, unique=True)),
            ],
            options={
                'verbose_name': 'tipomovimiento',
                'verbose_name_plural': 'tiposmovimiento',
            },
        ),
        migrations.CreateModel(
            name='Tiponovedadpersonal',
            fields=[
                ('idtiponovedad_personal', models.AutoField(primary_key=True, serialize=False)),
                ('novedad_personal', models.CharField(max_length=45, unique=True)),
            ],
            options={
                'verbose_name': 'tiponovedadpersonal',
                'verbose_name_plural': 'tiposnovedadpersonal',
            },
        ),
        migrations.CreateModel(
            name='Tiponovedadproducto',
            fields=[
                ('idtiponovedad_prodcuto', models.AutoField(primary_key=True, serialize=False)),
                ('novedad_producto', models.CharField(max_length=45, unique=True)),
            ],
            options={
                'verbose_name': 'Tiponovedadproducto',
                'verbose_name_plural': 'Tiposnovedadproducto',
            },
        ),
        migrations.CreateModel(
            name='TipoPQR',
            fields=[
                ('idtipo_pqr', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_pqr', models.CharField(max_length=45, unique=True)),
            ],
            options={
                'verbose_name': 'Tipopqr',
                'verbose_name_plural': 'Tipospqr',
            },
        ),
        migrations.CreateModel(
            name='Ubicacioninventario',
            fields=[
                ('idubicacion_inv', models.AutoField(primary_key=True, serialize=False)),
                ('ubicacion_inventario', models.CharField(max_length=45, unique=True)),
            ],
            options={
                'verbose_name': 'ubicacioninventario',
                'verbose_name_plural': 'ubicacionesnventario',
            },
        ),
        migrations.CreateModel(
            name='Usuarioid',
            fields=[
                ('idusuario', models.AutoField(primary_key=True, serialize=False)),
                ('usuario', models.CharField(max_length=45)),
                ('contrasena', models.CharField(max_length=25)),
            ],
            options={
                'verbose_name': 'usuarioID',
                'verbose_name_plural': 'usuariosID',
            },
        ),
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('iddireccion', models.AutoField(primary_key=True, serialize=False)),
                ('direccion', models.CharField(max_length=60)),
                ('barrio', models.CharField(max_length=45)),
                ('idciudad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventas.ciudad')),
            ],
            options={
                'verbose_name': 'direccion',
                'verbose_name_plural': 'direcciones',
            },
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('documentoidentidad', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('primer_nombre', models.CharField(max_length=45)),
                ('segundo_nombre', models.CharField(blank=True, max_length=45, null=True)),
                ('primer_apellido', models.CharField(max_length=45)),
                ('segundo_apellido', models.CharField(blank=True, max_length=45, null=True)),
                ('genero', models.CharField(max_length=20)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('idcontacto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ventas.contacto')),
                ('iddireccion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ventas.direccion')),
            ],
            options={
                'verbose_name': 'persona',
                'verbose_name_plural': 'personas',
            },
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('cod_empleado', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('fecha_ingreso', models.DateField()),
                ('salario', models.FloatField()),
                ('fecha_nacimiento', models.DateField()),
                ('rh', models.CharField(max_length=5)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('idarl', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventas.arl')),
                ('idcargo_empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventas.cargoempleado')),
                ('ideps', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventas.eps')),
                ('idfondo_pension', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventas.fondopension')),
                ('iddocumento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventas.persona')),
                ('idrolusuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventas.rolusuario')),
                ('idusuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventas.usuarioid')),
            ],
            options={
                'verbose_name': 'empleado',
                'verbose_name_plural': 'empleados',
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('cod_cliente', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('cupo_credito', models.IntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('iddocumento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventas.persona')),
                ('idtipo_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventas.tipocliente')),
                ('idtipo_comercio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventas.tipocomercio')),
            ],
            options={
                'verbose_name': 'cliente',
                'verbose_name_plural': 'clientes',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('cod_producto', models.CharField(max_length=15, primary_key=True, serialize=False, unique=True)),
                ('nombre_producto', models.CharField(max_length=45)),
                ('precio_venta', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descripcion_producto', models.CharField(max_length=45)),
                ('cantidad_productos', models.PositiveIntegerField()),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='productos')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('idcategoria_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventas.categoriaproducto')),
                ('idtalla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventas.talla')),
            ],
            options={
                'verbose_name': 'producto',
                'verbose_name_plural': 'productos',
            },
        ),
        migrations.CreateModel(
            name='Cotizacion',
            fields=[
                ('idcotizacion', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_cotizacion', models.DateTimeField(auto_now_add=True)),
                ('cantidad_productos', models.PositiveIntegerField()),
                ('valortotal_productos', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descuento', models.IntegerField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('cod_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventas.cliente')),
                ('cod_empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventas.empleado')),
                ('cod_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventas.producto')),
            ],
            options={
                'verbose_name': 'cotizacion',
                'verbose_name_plural': 'cotizaciones',
            },
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('idinventario', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_inventario', models.DateField(default=django.utils.timezone.now)),
                ('cantidad_productos', models.IntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('cod_empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventas.empleado')),
                ('cod_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventas.producto')),
                ('idtalla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventas.talla')),
                ('idtipo_movimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventas.tipomovimiento')),
                ('idubicacion_inventario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventas.ubicacioninventario')),
            ],
            options={
                'verbose_name': 'inventario',
                'verbose_name_plural': 'inventarios',
            },
        ),
        migrations.CreateModel(
            name='Novedadpersonal',
            fields=[
                ('idnovedadpersonal', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_inicio', models.DateField()),
                ('fechafin', models.DateField(blank=True, null=True)),
                ('descripcion', models.CharField(max_length=90)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('codigo_empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventas.empleado')),
                ('idtiponovedad_personal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventas.tiponovedadpersonal')),
            ],
            options={
                'verbose_name': 'novedadpersonal',
                'verbose_name_plural': 'novedadespersonal',
            },
        ),
        migrations.CreateModel(
            name='Novedadproducto',
            fields=[
                ('idnovedad_producto', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_novedad', models.DateField(default=django.utils.timezone.now)),
                ('descripcion', models.CharField(max_length=100)),
                ('cantidad_productos', models.PositiveIntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('cod_empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventas.empleado')),
                ('idinventario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventas.inventario')),
                ('cod_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventas.producto')),
                ('tiponovedad_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventas.tiponovedadproducto')),
            ],
            options={
                'verbose_name': 'novedadproducto',
                'verbose_name_plural': 'novedadesproducto',
            },
        ),
        migrations.CreateModel(
            name='Pqr',
            fields=[
                ('idpqr', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_inicio', models.DateTimeField(default=django.utils.timezone.now)),
                ('motivo_pqr', models.CharField(max_length=250)),
                ('fecha_cierre', models.DateField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('cod_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventas.cliente')),
                ('cod_empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventas.empleado')),
                ('idestadopqr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventas.estadopqr')),
                ('idtipopqr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventas.tipopqr')),
            ],
            options={
                'verbose_name': 'PQR',
                'verbose_name_plural': 'PQRS',
            },
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('idventa', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad_productos', models.IntegerField(blank=True, null=True)),
                ('descuento_venta', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('precio_venta', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_venta', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_venta', models.DateTimeField(default=django.utils.timezone.now)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('cod_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventas.cliente')),
                ('cod_empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventas.empleado')),
                ('cod_producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ventas.producto')),
            ],
            options={
                'verbose_name': 'venta',
                'verbose_name_plural': 'ventas',
            },
        ),
        migrations.CreateModel(
            name='Comprobanteventa',
            fields=[
                ('idcomprobante_venta', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_comprobante', models.DateTimeField(auto_now_add=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('idestado_comprobante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventas.estadocomprobante')),
                ('idforma_pago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventas.formapago')),
                ('idventa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventas.venta')),
            ],
            options={
                'verbose_name': 'compobanteventa',
                'verbose_name_plural': 'comprobantesventa',
            },
        ),
    ]
